apiVersion: v1
kind: PersistentVolume
metadata:
  name: datahub-pv8
  namespace: default
spec:
  storageClassName: microk8s-hostpath
  volumeMode: Filesystem
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /datahub
      