apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datadir-prerequisites-neo4j-community-0
  namespace: default
spec:
  storageClassName: microk8s-hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  volumeMode: Filesystem