kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
kubeadmConfigPatches:
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: ClusterConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  imageRepository: 0.0.0.0:5000/aiip
  nodeRegistration:
    kubeletExtraArgs:
      pod-infra-container-image: 0.0.0.0:5000/aiip/pause:3.1
- |
  apiVersion: kubeadm.k8s.io/v1beta2
  kind: InitConfiguration
  metadata:
    name: config
  networking:
    serviceSubnet: 10.0.0.0/16
  imageRepository: 0.0.0.0:5000/aiip
nodes:
- role: control-plane
  image: kindest/node:v1.29.10